// Define arrays of truth and dare challenges
const truthChallenges = [
    "What's the most embarrassing thing that has happened to you?",
    "Have you ever cheated on a test or exam?",
    "What's your biggest fear?",
    "What's a secret you've never told anyone?",
    "What's the weirdest dream you've ever had?",
    "What's the most embarrassing thing that has happened to you?",
"Have you ever lied to a friend to avoid hanging out with them?",
"What's your weirdest food craving?",
"Have you ever had a crush on someone in this room?",
"What's a movie you pretend to have seen but haven't?",
"Have you ever stolen something, even if it was small?",
"What's the most trouble you've ever been in with your parents?",
"Have you ever snooped through someone else's phone without them knowing?",
"What's your guilty pleasure TV show or movie?",
"Have you ever had a secret admirer?",
"What's a skill you've always wanted to learn but haven't?",
"Have you ever lied about your age?",
"What's your most irrational fear?",
"Have you ever cheated in a game or sport?",
"What's a bad habit you're trying to break?",
"Have you ever had a crush on a teacher?",
"What's the most embarrassing thing in your browser history?",
"Have you ever been caught talking to yourself?",
"What's something you regret doing or not doing?",
"Have you ever eaten food that fell on the floor?",
"What's the weirdest pet you've ever had or wanted?",
"Have you ever pretended to know something you had no clue about?",
"What's a lie you've told your parents?",
"Have you ever had a celebrity crush?",
"What's the most childish thing you still do as an adult?",
"Have you ever sent a text to the wrong person?",
"What's the most embarrassing thing you've done for a crush?",
"Have you ever been caught singing in the shower?",
"What's something you're scared to try?",
"Have you ever laughed so hard you cried?",
"What's a rumor you've spread about someone?",
"Have you ever had a wardrobe malfunction?",
"What's your most embarrassing childhood memory?",
"Have you ever talked to yourself in the mirror?",
"What's the silliest thing that makes you cry?",
"Have you ever faked being sick to get out of something?",
"What's a secret talent you have?",
"Have you ever picked your nose and eaten it?",
"What's the worst lie you've ever told?",
"Have you ever had an imaginary friend?",
"What's the most embarrassing text you've sent to the wrong person?",
"Have you ever lied to get out of a date?",
"What's something you're ashamed of enjoying?",
"Have you ever peed in a pool?",
"What's a TV show or movie you pretend to dislike but secretly love?",
"Have you ever cheated on a partner?",
"What's something you've stolen from a restaurant?",
"Have you ever been caught talking to an inanimate object?",
"What's a weird habit you have in the bathroom?",
"Have you ever cheated on a game or test in school?",
"What's the most embarrassing nickname you've ever had?",
"Have you ever pretended to know a famous person to impress someone?",
"What's a lie you've told your best friend?",
"Have you ever cheated in a board game?",
"What's the strangest dream you've ever had?",
"Have you ever pretended to be sick to skip school or work?",
"What's the most embarrassing thing you've searched for online?",
"Have you ever accidentally sent a message to the wrong group chat?",
"What's a secret you've never told your siblings?",
"Have you ever cheated on a card game?",
"What's the silliest thing you've argued about with a friend?",
"Have you ever laughed at a joke you didn't understand?",
"What's a guilty pleasure you have in music?",
"Have you ever lied about your favorite book or author?",
"What's a skill you've exaggerated on your resume or job application?",
"Have you ever pretended to like a gift you actually disliked?",
"What's the most embarrassing photo you have on your phone?",
"Have you ever pretended to be someone else on social media?",
"What's something you've done but would never do again?",
"Have you ever had a crush on someone much older or younger than you?",
"What's a secret you've kept from your best friend?",
"Have you ever cheated on a video game?",
"What's a secret talent you have that no one knows about?",
"Have you ever stolen something from a friend's house?",
"What's the most embarrassing thing you've said in front of a crush?",
"Have you ever snooped through someone's personal belongings?",
"What's a lie you've told to avoid getting in trouble?",
"Have you ever pretended to like a hobby or activity to fit in?",
"What's the most embarrassing thing you've worn in public?",
"Have you ever lied about your academic achievements?",
"What's a guilty pleasure TV show you've binge-watched?",
"Have you ever exaggerated a story to make it more interesting?",
"What's the most embarrassing way you've injured yourself?",
"Have you ever hidden a mistake you made at work or school?",
"What's a secret crush you've never revealed to anyone?",
"Have you ever pretended to know a foreign language you don't?",
"What's the silliest thing you've cried about as an adult?",
"Have you ever used someone else's toothbrush without them knowing?",
"What's the most embarrassing thing you've done while sleepwalking?",
"Have you ever blamed someone else for something you did?",
"What's a lie you've told to avoid a confrontation?",
"Have you ever pretended to like a type of food you dislike?",
"What's the most embarrassing thing you've accidentally shared on social media?",
"Have you ever cheated in a game of cards?",
"What's a skill you've claimed to have but can't actually do?",
"Have you ever lied to get out of a family gathering or event?",
"What's the most embarrassing text message you've received?",
"Have you ever pretended to be someone else online for fun?",
"What's a secret you've kept from your partner?",
"Have you ever lied about your age to get a discount or benefit?",
"What's the most embarrassing thing you've done on a date?",
"Have you ever pretended to like a type of music you hate?",
"What's a lie you've told to avoid going to the gym or working out?",
"Have you ever cheated in a game of hide and seek?",
"What's the most embarrassing thing you've posted on social media?",
"Have you ever pretended to be someone else to avoid someone?",
"What's a secret you've kept from your coworkers?",
"Have you ever cheated on a homework assignment or project?",
"What's the silliest thing you've been afraid of as a child?",
"Have you ever pretended to be someone else to prank someone?",
"What's the most embarrassing thing you've worn for a costume party?",
"Have you ever cheated in a video game and denied it?",
"What's a lie you've told to impress someone?",
"Have you ever pretended to know a language and spoke gibberish?",
"What's the most embarrassing thing you've done in front of a mirror?",
"Have you ever cheated in a game of chess?",
"What's a secret hobby you have that no one knows about?",
"Have you ever pretended to know a song's lyrics and mumbled along?",
"What's the most embarrassing thing you've done at a family gathering?",
"Have you ever cheated in a game of cards and got caught?",
"What's a lie you've told to avoid going to a family event?",
"Have you ever pretended to like a pet you actually dislike?",
"What's the most embarrassing thing you've said in a job interview?",
"Have you ever cheated in a board game and won?",
"What's a secret talent you have that surprises people?",
"Have you ever pretended to like a type of art you don't understand?",
"What's the most embarrassing thing you've done at a party?",
"Have you ever cheated on a test and got away with it?",
"What's a lie you've told to avoid going to a social gathering?",
"Have you ever pretended to know a famous person to get attention?",
"What's the most embarrassing thing you've done in a classroom?",
"Have you ever cheated in a game of Scrabble?",
"What's a secret goal you have for the future?",
"Have you ever pretended to like a book to fit in with a book club?",
"What's the most embarrassing thing you've said during a speech?",
"Have you ever cheated in a game of Monopoly?",
"What's a lie you've told to avoid going to a family reunion?",
"Have you ever pretended to like a sport you know nothing about?",
"What's the most embarrassing thing you've done at a wedding?",
"Have you ever cheated in a test and regretted it?",
"What's a secret skill you're working on improving?",
"Have you ever pretended to like a TV show just to fit in?",
"What's the most embarrassing thing you've done on a first date?",
"Have you ever cheated in a game of Pictionary?",
"What's a lie you've told to avoid going to a wedding?",
"Have you ever pretended to know a topic for a job interview?",
"What's the most embarrassing thing you've done during a presentation?",
"Have you ever cheated in a game of charades?",
"What's a secret place you like to go to for solitude?",
"Have you ever pretended to like a hobby to impress someone?",
"What's the most embarrassing thing you've said in a meeting?",
"Have you ever cheated in a game of trivia?",
"What's a lie you've told to avoid going to a concert?",
"Have you ever pretended to know a subject to join a conversation?",
"What's the most embarrassing thing you've done at a job interview?",
"Have you ever cheated in a game of Uno?",
"What's a secret dream you have for your future?",
"Have you ever pretended to like a band just to fit in?",
"What's the most embarrassing thing you've done in front of your boss?",
"Have you ever cheated in a game of poker?",
"What's a lie you've told to avoid going to a music festival?",
"Have you ever pretended to know a skill for a job application?",
"What's the most embarrassing thing you've said in a group chat?",
"Have you ever cheated in a game of Scrabble and lost?",
"What's a secret talent you have that you're proud of?",
"Have you ever pretended to like a movie just to join a conversation?",
"What's the most embarrassing thing you've done in a team meeting?",
"Have you ever cheated in a game of chess and lost?",
"What's a lie you've told to avoid going to a sports event?",
"Have you ever pretended to know a language to impress someone?",
"What's the most embarrassing thing you've done during a conference call?",
"Have you ever cheated in a game of Monopoly and lost?",
"What's a secret hobby you've recently discovered?",
"Have you ever pretended to like a book to be part of a book club?",
"What's the most embarrassing thing you've said during a team presentation?",
"Have you ever cheated in a test and got caught?",
"What's a lie you've told to avoid going to a family gathering?",
"Have you ever pretended to like a sport you know nothing about and got caught?",
"What's the most embarrassing thing you've done during a family reunion?",
"Have you ever cheated in a game of Pictionary and got caught?",
"What's a secret goal you have for your career?",
"Have you ever pretended to know a topic for a job interview and got caught?",
"What's the most embarrassing thing you've said during a job interview?",
"Have you ever cheated in a game of charades and got caught?",
"What's a secret place you like to go to for relaxation?",
"Have you ever pretended to like a hobby to impress someone and got caught?",
"What's the most embarrassing thing you've done in front of your colleagues?",
"Have you ever cheated in a game of Uno and got caught?",
"What's a secret dream you have for your personal life?",
"Have you ever pretended to like a band to fit in and got caught?",
"What's the most embarrassing thing you've said in front of your supervisor?",
"Have you ever cheated in a game of poker and got caught?",
"What's a secret talent you have that you've never revealed to anyone?",
"Have you ever pretended to like a movie just to join a conversation and got caught?",
"What's the most embarrassing thing you've done in front of your clients?",
"Have you ever cheated in a game of chess and got caught?",
"What's a lie you've told to avoid going to a music festival and got caught?",
"Have you ever pretended to know a skill for a job application and got caught?",
"What's the most embarrassing thing you've said in a group chat and got caught?",
"Have you ever cheated in a game of Scrabble and lost, and felt guilty about it?",
"What's a secret talent you have that you're proud of but rarely showcase?",
"Have you ever pretended to like a book to be part of a book club and later admitted it?",
"What's the most embarrassing thing you've said during a team presentation and laughed it off?",
"Have you ever cheated in a test and got caught, and had to face the consequences?",
"What's a lie you've told to avoid going to a family gathering, and your family found out?",
"Have you ever pretended to like a sport you know nothing about and got caught, leading to an awkward situation?",
"What's the most embarrassing thing you've done during a family reunion and later became the family legend?",
"Have you ever cheated in a game of Pictionary and got caught, making the game more entertaining?",
"What's a secret goal you have for your career, and how are you working towards it?",
"Have you ever pretended to know a topic for a job interview and got caught, leading to a humorous interview?",
"What's the most embarrassing thing you've said during a job interview and still got the job?",
"Have you ever cheated in a game of charades and got caught, resulting in laughter?",
"What's a secret place you like to go to for relaxation, and why is it your peaceful haven?",
"Have you ever pretended to like a hobby to impress someone and got caught, but it turned into a funny story?",
"What's the most embarrassing thing you've done in front of your colleagues, and how did they react?",
"Have you ever cheated in a game of Uno and got caught, causing uproarious laughter?",
"What's a secret dream you have for your personal life, and how do you plan to achieve it?",
"Have you ever pretended to like a band to fit in and got caught, leading to unexpected bonding?",
"What's the most embarrassing thing you've said in front of your supervisor, and how did they respond?",
"Have you ever cheated in a game of poker and got caught, making the game more entertaining?",
"What's a secret talent you have that you've never revealed to anyone, and why not?",
"Have you ever pretended to like a movie just to join a conversation and got caught, resulting in laughter?",
"What's the most embarrassing thing you've done in front of your clients, and how did they react?",
"Have you ever cheated in a game of chess and got caught, leading to a memorable match?",
"What's a lie you've told to avoid going to a music festival and got caught, creating an amusing story?",
"Have you ever pretended to know a skill for a job application and got caught, but still landed the job?",
"What's the most embarrassing thing you've said in a group chat and got caught, sparking laughter?",
"Have you ever cheated in a game of Scrabble and lost, and how did you handle the defeat?",
"What's a secret talent you have that you're proud of but rarely showcase, and why?",
"Have you ever pretended to like a book to be part of a book club and later admitted it, leading to interesting book discussions?",
"What's the most embarrassing thing you've said during a team presentation and laughed it off, making the team bond even more?",
"Have you ever cheated in a test and got caught, and how did you make amends?",
"What's a lie you've told to avoid going to a family gathering, and did your family ever find out the truth?",
"Have you ever pretended to like a sport you know nothing about and got caught, resulting in amusing sports conversations?",
"What's the most embarrassing thing you've done during a family reunion and later became the family legend, celebrated at every reunion?",
"Have you ever cheated in a game of Pictionary and got caught, creating unforgettable moments?",
"What's a secret goal you have for your career, and what steps are you taking to achieve it?",
"Have you ever pretended to know a topic for a job interview and got caught, leading to a memorable interview experience?",
"What's the most embarrassing thing you've said during a job interview and still managed to impress the interviewer?",
"Have you ever cheated in a game of charades and got caught, turning it into a hilarious game night?",
"What's a secret place you like to go to for relaxation, and how do you find solace there?",
"Have you ever cheated in a game of Uno and got caught, turning it into an evening of laughter?",
"What's a secret dream you have for your personal life, and what steps are you taking to make it a reality?",
"Have you ever pretended to like a band to fit in and got caught, leading to newfound music interests?",
"What's the most embarrassing thing you've said in front of your supervisor, and how did it affect your work dynamic?",
"Have you ever cheated in a game of poker and got caught, making the poker night unforgettable?",
"What's a secret talent you have that you've never revealed to anyone, and why haven't you shared it?",
"Have you ever pretended to like a movie just to join a conversation and got caught, resulting in movie recommendations?",
"What's the most embarrassing thing you've done in front of your clients, and how did it impact your professional relationships?",
"Have you ever cheated in a game of chess and got caught, leading to epic chess matches?",
"What's a lie you've told to avoid going to a music festival and got caught, creating a hilarious festival experience?",
"Have you ever pretended to know a skill for a job application and got caught, but it didn't deter you from pursuing that skill?",
"What's the most embarrassing thing you've said in a group chat and got caught, resulting in inside jokes?",
"Have you ever cheated in a game of Scrabble and lost, and did it motivate you to improve your vocabulary?",
"What's a secret talent you have that you're proud of but rarely showcase, and what would it take for you to display it more often?",
"Have you ever pretended to like a book to be part of a book club and later admitted it, leading to diverse reading selections?",
"What's the most embarrassing thing you've said during a team presentation and laughed it off, fostering camaraderie within the team?",
"Have you ever cheated in a test and got caught, and how did you make amends and improve your study habits?",
"What's a lie you've told to avoid going to a family gathering, and did it result in a hilarious family story?",
"Have you ever pretended to like a sport you know nothing about and got caught, initiating engaging sports discussions with friends?",
"What's the most embarrassing thing you've done during a family reunion and later became the go-to anecdote at gatherings?",
"Have you ever cheated in a game of Pictionary and got caught, turning it into an annual tradition of laughter?",
"What's a secret goal you have for your career, and what steps are you taking to make progress toward it?",
"Have you ever pretended to know a topic for a job interview and got caught, but it ultimately led to a better-suited job opportunity?",
"What's the most embarrassing thing you've said during a job interview and still secured the job, showcasing your adaptability?",
"Have you ever cheated in a game of charades and got caught, creating memorable game nights with friends?",
"What's a secret place you like to go to for relaxation, and how does it bring you peace?",
"Have you ever cheated in a game of Uno and got caught, sparking laughter and friendly competition?",
"What's a secret dream you have for your personal life, and how do you plan to take steps toward fulfillment?",
"Have you ever pretended to like a band to fit in and got caught, leading to shared concert experiences?",
"What's the most embarrassing thing you've said in front of your supervisor, and how did it affect your professional relationship?",
"Have you ever cheated in a game of poker and got caught, turning poker nights into memorable gatherings?",
"What's a secret talent you have that you've never revealed to anyone, and what's holding you back from sharing it?",
"Have you ever pretended to like a movie just to join a conversation and got caught, resulting in lively film discussions?",
"What's the most embarrassing thing you've done in front of your clients, and how did it impact your business relationships?",
"Have you ever cheated in a game of chess and got caught, leading to entertaining chess battles with friends?",
"What's a lie you've told to avoid going to a music festival and got caught, turning it into a memorable festival experience?",
"Have you ever pretended to know a skill for a job application and got caught, but it motivated you to develop that skill?",
"What's the most embarrassing thing you've said in a group chat and got caught, resulting in ongoing humor among friends?",
"Have you ever cheated in a game of Scrabble and lost, and did it inspire you to become a better wordplay enthusiast?",
"What's a secret talent you have that you're proud of but rarely showcase, and what would it take for you to share it more openly?",
"Have you ever pretended to like a book to be part of a book club and later admitted it, leading to diverse and engaging reading selections?",
"What's the most embarrassing thing you've said during a team presentation and laughed it off, creating a stronger team bond?",
"Have you ever cheated in a test and got caught, and how did you learn from the experience and improve your academic ethics?",
"What's a lie you've told to avoid going to a family gathering, and did it result in a comical family story that's frequently retold?",
"Have you ever pretended to like a sport you know nothing about and got caught, sparking enjoyable sports discussions with friends?",
"What's the most embarrassing thing you've done during a family reunion and later became the cherished tale of the family?",
"Have you ever cheated in a game of Pictionary and got caught, turning game nights into unforgettable and hilarious events?",
"What's a secret goal you have for your career, and how are you actively pursuing it?",
"Have you ever pretended to know a topic for a job interview and got caught, but it led to a more suitable job opportunity?",
"What's the most embarrassing thing you've said during a job interview and still managed to impress the interviewer with your resilience?",
"Have you ever cheated in a game of charades and got caught, making game nights with friends even more entertaining?",
"What's a secret place you like to go to for relaxation, and how does it provide you with a sense of tranquility?",
"Have you ever cheated in a game of Uno and got caught, resulting in laughter and a more competitive spirit among friends?",
"What's a secret dream you have for your personal life, and what steps are you taking to turn that dream into reality?",
"Have you ever pretended to like a band to fit in and got caught, leading to shared concert experiences and newfound musical interests?",
"What's the most embarrassing thing you've said in front of your supervisor, and how did it impact your professional relationship, if at all?",
"Have you ever cheated in a game of poker and got caught, turning poker nights into memorable and enjoyable gatherings?",
"What's a secret talent you have that you've never shared with anyone, and why have you kept it hidden?",
"Have you ever pretended to like a movie just to join a conversation and got caught, resulting in engaging discussions and movie nights?",
"What's the most embarrassing thing you've done in front of your clients, and how did it affect your business relationships, positively or negatively?",
"Have you ever cheated in a game of chess and got caught, sparking entertaining and competitive chess matches with friends?",
"What's a lie you've told to avoid attending a music festival and got caught, turning it into a memorable and amusing festival experience?",
"Have you ever pretended to possess a skill for a job application and got caught, but it motivated you to develop that skill and excel?",
"What's the most embarrassing thing you've said in a group chat and got caught, resulting in ongoing humor and camaraderie among friends?",
];

const dareChallenges = [
    "Call a random contact from your phone and say 'I love you.'",
    "Dance for 30 seconds without music.",
    "Eat a spoonful of hot sauce.",
    "Text your crush and confess your feelings.",
    "Do 10 push-ups right now.",
    "Dance for 30 seconds without music.",
"Call a random contact from your phone and say 'I love you.'",
"Text your crush and confess your feelings.",
"Eat a spoonful of hot sauce.",
"Let someone in the group choose a hairstyle for you and style your hair that way.",
"Put an ice cube down your shirt and leave it there until it melts.",
"Prank call a friend or family member.",
"Wear socks on your hands for the next three rounds.",
"Speak in an accent for the rest of the game.",
"Do your best impression of a famous celebrity.",
"Talk like a pirate for the next five minutes.",
"Put on a blindfold and let someone feed you a mystery food.",
"Wear a funny hat for the next two rounds.",
"Sing a song chosen by the group, no matter how badly.",
"Put on lipstick (if available) without using a mirror.",
"Speak gibberish for the next three rounds.",
"Text a random person from your contacts and say, 'I'm a purple ninja.'",
"Do your best robot dance for 30 seconds.",
"Wear a sign that says, 'I'm a superstar' for the next round.",
"Do jumping jacks until it's your turn again.",
"Take a silly selfie and post it on your social media.",
"Put on sunglasses and keep them on for the next two rounds.",
"Draw a funny face on your hand and have a conversation with it.",
"Recite the alphabet backward without making a mistake.",
"Spin around in circles for 10 seconds and try to walk straight afterward.",
"Talk like a robot for the next five minutes.",
"Act out your favorite movie scene.",
"Hop on one foot while singing 'Happy Birthday' to yourself.",
"Put on a sock puppet show for the group.",
"Speak in rhymes for the next two rounds.",
"Tell a funny joke, even if it's a bad one.",
"Try to juggle three random objects for 30 seconds.",
"Wear a mustache drawn on your finger for the next round.",
"Make up a short rap about something in the room.",
"Pretend you're a news anchor and report on something silly.",
"Act out a scene from your favorite TV show or movie.",
"Try to do a handstand (safely) against a wall.",
"Tell a 'dad joke' that makes everyone laugh.",
"Try to do the moonwalk dance.",
"Make up a funny commercial for a random product.",
"Wear a sock as a glove for the next two rounds.",
"Mime your favorite hobby, and others have to guess what it is.",
"Speak in slow motion for the next five minutes.",
"Do your best impression of a famous movie character.",
"Wear a towel as a cape and pretend to be a superhero for the next round.",
"Balance a spoon on your nose for as long as you can.",
"Try to do a cartwheel (if it's safe).",
"Speak in a British accent for the next three rounds.",
"Create a short, funny song about a random object in the room.",
"Wear a funny mask for the next round.",
"Make up a silly dance and perform it.",
"Pretend to be a different animal for the next round.",
"Balance a book on your head for as long as you can.",
"Sing a song while holding your nose.",
"Talk in a whisper for the next three rounds.",
"Put an ice cube in your mouth and let it melt.",
"Act like you're underwater for the next two rounds.",
"Pretend to be a robot and interact with others that way.",
"Hop on one foot while saying the alphabet backward.",
"Wear a silly hat and keep it on for the rest of the game.",
"Speak in a foreign language (real or made-up) for the next round.",
"Make up a rap about a random object in the room.",
"Walk like a penguin for the next two rounds.",
"Try to lick your elbow (you probably can't).",
"Speak in rhyme for the next three rounds.",
"Wear a paper bag as a hat for the next round.",
"Pretend to be a famous athlete and give an acceptance speech.",
"Do your best impression of a famous politician.",
"Walk on tiptoes for the next two rounds.",
"Speak in a high-pitched voice for the rest of the game.",
"Pretend to be a tour guide and describe an imaginary place.",
"Balance a spoon on your nose and try to walk around.",
"Make up a short poem about a random object in the room.",
"Wear socks on your hands and try to eat a snack.",
"Speak in a deep voice for the next three rounds.",
"Act like you're in a slow-motion movie for the next round.",
"Pretend to be a famous chef and describe your signature dish.",
"Try to whistle a tune without using your lips.",
"Wear a scarf as a headband for the rest of the game.",
"Speak in a whispery, ghost-like voice for the next two rounds.",
"Pretend to be a stand-up comedian and tell a joke.",
"Balance a book on your head and walk around the room.",
"Do your best impression of a famous singer.",
"Speak in a foreign accent for the next three rounds.",
"Act like you're in a silent movie for the next round.",
"Pretend to be a famous actor and give an acceptance speech.",
"Walk in slow motion for the next two rounds.",
"Speak like a cartoon character for the rest of the game.",
"Pretend to be a news reporter and cover a random event.",
"Balance a spoon on your nose and hop on one foot.",
"Make up a short story about a random object in the room.",
"Wear a pair of sunglasses indoors for the next round.",
"Speak in a different language (real or made-up) for the next three rounds.",
"Act like you're in a horror movie for the next round.",
"Pretend to be a famous director and give instructions for a scene.",
"Walk with exaggerated, big steps for the next two rounds.",
"Speak as fast as you can for the rest of the game.",
"Pretend to be a game show host and ask trivia questions.",
"Balance a book on your head and sing a song.",
"Do your best impression of a famous comedian.",
];

// Initialize variables
const truthButton = document.getElementById("truthButton");
const dareButton = document.getElementById("dareButton");
const challenge = document.getElementById("challenge");
const truthOrDare = document.getElementById("truthOrDare");
const dareOrTruth = document.getElementById("dareOrTruth");

// Function to pick a random challenge from an array
function getRandomChallenge(challengesArray) {
    const randomIndex = Math.floor(Math.random() * challengesArray.length);
    return challengesArray[randomIndex];
}

// Event listener for the "Truth" button
truthButton.addEventListener("click", () => {
    const truthChallenge = getRandomChallenge(truthChallenges);
    truthOrDare.style.color = "blue";
    dareOrTruth.style.color = "red";
    challenge.textContent = `Truth: ${truthChallenge}`;
    challenge.style.color = "hotpink";
});

// Event listener for the "Dare" button
dareButton.addEventListener("click", () => {
    const dareChallenge = getRandomChallenge(dareChallenges);
    truthOrDare.style.color = "red";
    dareOrTruth.style.color = "blue";
    challenge.textContent = `Dare: ${dareChallenge}`;
    challenge.style.color = "red";
});
